# Generated by Django 3.2.4 on 2021-12-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
