# Generated by Django 3.2.4 on 2022-05-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_block_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='lock_time',
        ),
    ]
